# Generated by Django 2.2.1 on 2019-08-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(max_length=6000, verbose_name='Description')),
                ('category', models.CharField(max_length=128, verbose_name='Category')),
                ('img', models.ImageField(upload_to='album/user_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Photographer')),
            ],
        ),
    ]
