# Generated by Django 2.2.1 on 2019-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('animal', 'animal'), ('art', 'art'), ('landscape', 'landscape'), ('nature', 'nature'), ('people', 'people'), ('sky', 'sky')], default='art', max_length=16, verbose_name='Category'),
        ),
    ]
