# Generated by Django 2.2.1 on 2019-08-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20190801_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
